apiVersion: v1
kind: Service
metadata:
  name: external-lb
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - name: ancdb
    port: 5432
    targetPort: "5432-port"
  - name: ancbe
    port: 8080
    targetPort: "8080-port"
  - name: ancfe
    port: 80
    targetPort: "80-port"
  selector:
    lbtype: external